/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LyricStudioImport } from './routes/lyric-studio'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LyricStudioRoute = LyricStudioImport.update({
  id: '/lyric-studio',
  path: '/lyric-studio',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/lyric-studio': {
      id: '/lyric-studio'
      path: '/lyric-studio'
      fullPath: '/lyric-studio'
      preLoaderRoute: typeof LyricStudioImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lyric-studio': typeof LyricStudioRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lyric-studio': typeof LyricStudioRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/lyric-studio': typeof LyricStudioRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lyric-studio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lyric-studio'
  id: '__root__' | '/' | '/lyric-studio'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LyricStudioRoute: typeof LyricStudioRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LyricStudioRoute: LyricStudioRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/lyric-studio"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/lyric-studio": {
      "filePath": "lyric-studio.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
